config/routes.rb
Rails.application.routes.draw do

  resources :workouts
  resources :exercises
  root 'workouts#index'

end

app/models/exercise.rb
class Exercise < ActiveRecord::Base

  has_many :workouts, through: :workout_exercises

end

app/models/workout.rb
class Workout < ActiveRecord::Base
  has_many :exercises, through: :workout_exercises
end

app/models/workout_exercise.rb
class WorkoutExercise < ActiveRecord::Base
end

app/controllers/application_controller.rb
require "application_responder"

class ApplicationController < ActionController::Base
  self.responder = ApplicationResponder
  respond_to :html

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/exercises_controller.rb
class ExercisesController < ApplicationController

  def index
    @exercises = Exercise.all
  end

end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController

  respond_to :js, :html

  def index
    @workouts = Workout.all
  end

  def new
    @workout = Workout.new
  end

  def create
    @workout = Workout.new(workout_params)
    @workout.update_attributes(workout_params)
  end

  private

    def workout_params
      params.require(:workout).permit(:date)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/workouts_helper.rb
module WorkoutsHelper
end

app/views/exercises/index.html.erb
<div class = "container" >
  <div class = "jumbotron">
    <h1>Exercises</h1>
    <div class = "row">
      <div class = "col-xs-2">
        <ul class = "list-group">
          <% @exercises.each do |e| %>
            <li class = "list-group-item"><%= e.name %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workoutlog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/workouts/_form.html.erb
<%= form_for @workout, remote: true do |f| %>
  <%= f.date_select :date %>
  <%= f.button :submit %>
<% end %>

app/views/workouts/create.js.erb
$("#new-workout").slideUp(350);

app/views/workouts/index.html.erb
<div class = "container" >
  <div class = "jumbotron">
    <h1>Workouts</h1>
    <div class = "row">
      <div class = "col-xs-2">
        <ul class = "list-group">
          <% @workouts.each do |w| %>
            <li class = "list-group-item"><%= w.date %></li>
          <% end %>
        </ul>
      </div>
      <div class = "col-xs-6" id = "new-workout">
      </div>
    </div>
    <div class = "row">
      <%= link_to "New Workout", new_workout_path, remote: true %>
    </div>
  </div>
</div>

app/views/workouts/new.js.erb
$("#new-workout").html("<%= j (render 'form') %>");
$("#new-workout").slideDown(350);